version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: assethub_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: assethub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data: