server.port=8080

spring.datasource.url=jdbc:postgresql://ep-crimson-feather-alcn04mi-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xe3ABhiPv6NT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false



// Configurare server SMTP pentru mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=assethub.draxlmaier@gmail.com
spring.mail.password=yshunbvymslrufpp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=O_CHIE_FOARTE_LUNGA_SI_COMPLEXA_PE_CARE_NU_O_STIE_NIMENI    



