server.port=8080

spring.datasource.url=url-ul bazei de date
spring.datasource.username=username-ul
spring.datasource.password=parola
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false



// Configurare server SMTP pentru mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email
spring.mail.password=parola_mail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=O_CHIE_FOARTE_LUNGA_SI_COMPLEXA_PE_CARE_NU_O_STIE_NIMENI    



