server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/assethub_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=O_CHIE_FOARTE_LUNGA_SI_COMPLEXA_PE_CARE_NU_O_STIE_NIMENI